# Generated by Django 5.0.6 on 2024-05-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='added',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insight',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
