# Generated by Django 5.0.6 on 2024-05-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_insight_intensity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='likelihood',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insight',
            name='relevance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
